// AUTO-GENERATED by scripts/generate-lending-reports.ts - do not edit by hand.
import type { MarketReport } from "../../types";
import r0 from "./development-exit-refinance-monitor-h1-2026";
import r1 from "./development-lending-monitor-east-of-england-h1-2026";
import r2 from "./development-lending-monitor-h1-2026";
import r3 from "./development-lending-monitor-london-and-south-east-h1-2026";
import r4 from "./development-lending-monitor-midlands-h1-2026";
import r5 from "./development-lending-monitor-north-east-and-yorkshire-h1-2026";
import r6 from "./development-lending-monitor-north-west-h1-2026";
import r7 from "./development-lending-monitor-south-west-h1-2026";
import r8 from "./development-lending-monitor-wales-h1-2026";
import r9 from "./mezzanine-junior-debt-monitor-h1-2026";

export const LENDING_REPORTS: MarketReport[] = [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9];
