/**
 * Market Intelligence Data Loader
 *
 * Loads the Claude-generated editorial JSON for a market intelligence report,
 * and combines it with the underlying planning + sold-data + town-stats it
 * was generated from. Read at build/ISR time.
 */

import fs from "fs";
import path from "path";

import type { MarketIntelligenceLocation } from "@/lib/market-intelligence-locations";
import {
  getPlanningData,
  getSoldData,
  getTownStats,
  type PlanningData,
  type SoldData,
  type TownStats,
} from "@/lib/local-market-data";

/** Claude-generated editorial content for a town's MI report. */
export interface MarketIntelligenceEditorial {
  slug: string;
  name: string;
  generatedAt: string;
  reportPeriod: string;
  /** SEO title + page H1 */
  headline: string;
  /** Sub-headline shown under H1 */
  subhead: string;
  metaDescription: string;
  /** 2-3 sentence summary at the top */
  lead: string;
  /** Generated by Claude from sold + stats data */
  marketCommentary: string;
  /** Pipeline analysis — narrative around planning data (or fallback if data missing) */
  pipelineCommentary: string;
  /** Recent sales narrative */
  soldDataCommentary: string;
  /** What this means for developers seeking finance */
  developerImplications: string;
  /** Forward outlook */
  outlook: string;
  /** Optional pull quote */
  pullQuote?: string;
  /** Topical tags (used for related articles) */
  tags: string[];
  /** Editorial-curated list of stand-out applications worth highlighting */
  highlightedApplications?: Array<{
    reference: string;
    headline: string;
    summary: string;
  }>;
}

export interface MarketIntelligenceReport {
  editorial: MarketIntelligenceEditorial;
  location: MarketIntelligenceLocation;
  planning: PlanningData | null;
  sold: SoldData | null;
  stats: TownStats | null;
}

const EDITORIAL_DIR = "data/generated/market-intelligence";

export function getEditorial(slug: string): MarketIntelligenceEditorial | null {
  const filePath = path.join(process.cwd(), EDITORIAL_DIR, `${slug}.json`);
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as MarketIntelligenceEditorial;
  } catch {
    return null;
  }
}

export function getMarketIntelligenceReport(
  location: MarketIntelligenceLocation
): MarketIntelligenceReport | null {
  const editorial = getEditorial(location.slug);
  if (!editorial) return null;
  return {
    editorial,
    location,
    planning: getPlanningData(location.countySlug, location.townSlug),
    sold: getSoldData(location.countySlug, location.townSlug),
    stats: getTownStats(location.countySlug, location.townSlug),
  };
}

export function listGeneratedSlugs(): string[] {
  const dir = path.join(process.cwd(), EDITORIAL_DIR);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}
