/**
 * Master registry of all Construction Capital microsites.
 *
 * Each entry maps a microsite repo to its corresponding CC location page
 * so that scripts can:
 *   - Generate listicle content with correct backlinks
 *   - Update footer links to point to the right CC page
 *   - Audit deployment status across the network
 *
 * Usage:
 *   import { MICROSITES, getMicrositeBySlug } from '../microsites.config';
 */

export interface MicrositeConfig {
  /** Short identifier used in CLI commands (e.g., --site manchester-dev) */
  slug: string;
  /** GitHub repo name (under the authenticated user's account) */
  repoName: string;
  /** Primary production domain */
  domain: string;
  /** Site type: development-finance | bridging | niche */
  type: "development-finance" | "bridging" | "niche";
  /** CC county slug (from uk-locations-data.ts) */
  county: string;
  /** CC town slug (from uk-locations-data.ts) */
  town: string;
  /** Full CC location page URL */
  ccLocationUrl: string;
  /** Display name used in content (e.g., "Manchester Development Finance") */
  brandName: string;
  /** The town/city name for content generation */
  locationName: string;
  /** Hosting provider for deployment context */
  hostingProvider: "netlify" | "vercel" | "aws" | "railway" | "azure" | "google" | "other";
  /** Current status */
  status: "live" | "built" | "pending";
}

const CC_BASE = "https://constructioncapital.co.uk";

// ── Development Finance Sites ───────────────────────────────────────────────

const DEVELOPMENT_FINANCE_SITES: MicrositeConfig[] = [
  {
    slug: "manchester-dev",
    repoName: "manchesterdevelopmentfinancd",
    domain: "manchesterdevelopmentfinance.com",
    type: "development-finance",
    county: "greater-manchester",
    town: "manchester",
    ccLocationUrl: `${CC_BASE}/locations/greater-manchester/manchester`,
    brandName: "Manchester Development Finance",
    locationName: "Manchester",
    hostingProvider: "netlify",
    status: "live",
  },
  {
    slug: "london-dev",
    repoName: "londondevelopmentfinance",
    domain: "londondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "croydon", // London-wide, mapped to GL
    ccLocationUrl: `${CC_BASE}/locations/greater-london/croydon`,
    brandName: "London Development Finance",
    locationName: "London",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "birmingham-dev",
    repoName: "birminghamdevelopmentfinance",
    domain: "birminghamdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "west-midlands",
    town: "birmingham",
    ccLocationUrl: `${CC_BASE}/locations/west-midlands/birmingham`,
    brandName: "Birmingham Development Finance",
    locationName: "Birmingham",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "sheffield-dev",
    repoName: "sheffielddevelopmentfinance",
    domain: "sheffielddevelopmentfinance.co.uk",
    type: "development-finance",
    county: "south-yorkshire",
    town: "sheffield",
    ccLocationUrl: `${CC_BASE}/locations/south-yorkshire/sheffield`,
    brandName: "Sheffield Development Finance",
    locationName: "Sheffield",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "leeds-dev",
    repoName: "leedsdevelopmentfinance",
    domain: "leedsdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "west-yorkshire",
    town: "leeds",
    ccLocationUrl: `${CC_BASE}/locations/west-yorkshire/leeds`,
    brandName: "Leeds Development Finance",
    locationName: "Leeds",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "bristol-dev",
    repoName: "bristoldevelopmentfinance",
    domain: "bristoldevelopmentfinance.co.uk",
    type: "development-finance",
    county: "bristol",
    town: "bristol-city-centre",
    ccLocationUrl: `${CC_BASE}/locations/bristol/bristol-city-centre`,
    brandName: "Bristol Development Finance",
    locationName: "Bristol",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "barnet-dev",
    repoName: "barnetdevelopmentfinance",
    domain: "barnetdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "barking", // Barnet not in CC data — closest GL borough
    ccLocationUrl: `${CC_BASE}/locations/greater-london/barking`,
    brandName: "Barnet Development Finance",
    locationName: "Barnet",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "bexley-dev",
    repoName: "bexleydevelopmentfinance",
    domain: "bexleydevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "woolwich",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/woolwich`,
    brandName: "Bexley Development Finance",
    locationName: "Bexley",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "brent-dev",
    repoName: "brentdevelopmentfinance",
    domain: "brentdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "wembley",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/wembley`,
    brandName: "Brent Development Finance",
    locationName: "Brent",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "bromley-dev",
    repoName: "bromleydevelopmentfinance",
    domain: "bromleydevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "lewisham",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/lewisham`,
    brandName: "Bromley Development Finance",
    locationName: "Bromley",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "camden-dev",
    repoName: "camdendevelopmentfinancev2",
    domain: "camdendevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Camden Development Finance",
    locationName: "Camden",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "chelsea-dev",
    repoName: "chelseadevelopmentfinance",
    domain: "chelseadevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Chelsea Development Finance",
    locationName: "Chelsea",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "cityoflondon-dev",
    repoName: "cityoflondondevelopmentfinance",
    domain: "cityoflondondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "bermondsey",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/bermondsey`,
    brandName: "City of London Development Finance",
    locationName: "City of London",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "croydon-dev",
    repoName: "croydondevelopmentfinance",
    domain: "croydondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "croydon",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/croydon`,
    brandName: "Croydon Development Finance",
    locationName: "Croydon",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "ealing-dev",
    repoName: "ealingdevelopmentfinance",
    domain: "ealingdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "ealing",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/ealing`,
    brandName: "Ealing Development Finance",
    locationName: "Ealing",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "enfield-dev",
    repoName: "enfielddevelopmentfinance",
    domain: "enfielddevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "tottenham",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/tottenham`,
    brandName: "Enfield Development Finance",
    locationName: "Enfield",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "fulham-dev",
    repoName: "fulhamdevelopmentfinance",
    domain: "fulhamdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Fulham Development Finance",
    locationName: "Fulham",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "greenwich-dev",
    repoName: "Greenwichdevelopmentfinance",
    domain: "greenwichdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "woolwich",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/woolwich`,
    brandName: "Greenwich Development Finance",
    locationName: "Greenwich",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "hackney-dev",
    repoName: "hackneydevelopmentfinance",
    domain: "hackneydevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Hackney Development Finance",
    locationName: "Hackney",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "hammersmith-dev",
    repoName: "hammersmithdevelopmentfinance",
    domain: "hammersmithdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "ealing",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/ealing`,
    brandName: "Hammersmith Development Finance",
    locationName: "Hammersmith",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "haringey-dev",
    repoName: "haringeydevelopmentfinance",
    domain: "haringeydevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "tottenham",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/tottenham`,
    brandName: "Haringey Development Finance",
    locationName: "Haringey",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "islington-dev",
    repoName: "islingtondevelopmentfinance",
    domain: "islingtondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Islington Development Finance",
    locationName: "Islington",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "lambeth-dev",
    repoName: "lambethdevelopmentfinance",
    domain: "lambethdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Lambeth Development Finance",
    locationName: "Lambeth",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "southwark-dev",
    repoName: "southwarkdevelopmentfinance",
    domain: "southwarkdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "bermondsey",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/bermondsey`,
    brandName: "Southwark Development Finance",
    locationName: "Southwark",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "wandsworth-dev",
    repoName: "wandsworthdevelopmentfinance",
    domain: "wandsworthdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Wandsworth Development Finance",
    locationName: "Wandsworth",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "westminster-dev",
    repoName: "westminsterdevelopmentfinance",
    domain: "westminsterdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "bermondsey",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/bermondsey`,
    brandName: "Westminster Development Finance",
    locationName: "Westminster",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "barking-dev",
    repoName: "barkingdevelopmentfinance",
    domain: "barkingdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "barking",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/barking`,
    brandName: "Barking Development Finance",
    locationName: "Barking",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "harrow-dev",
    repoName: "harrowdevelopmentfinance",
    domain: "harrowdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "wembley",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/wembley`,
    brandName: "Harrow Development Finance",
    locationName: "Harrow",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "havering-dev",
    repoName: "haveringdevelopmentfinance",
    domain: "haveringdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "barking",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/barking`,
    brandName: "Havering Development Finance",
    locationName: "Havering",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "hillingdon-dev",
    repoName: "hillingdondevelopmentfinance",
    domain: "hillingdondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hounslow",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hounslow`,
    brandName: "Hillingdon Development Finance",
    locationName: "Hillingdon",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "hounslow-dev",
    repoName: "hounslowdevelopmentfinance",
    domain: "hounslowdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hounslow",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hounslow`,
    brandName: "Hounslow Development Finance",
    locationName: "Hounslow",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "kingston-dev",
    repoName: "kingstondevelopmentfinance",
    domain: "kingstondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Kingston Development Finance",
    locationName: "Kingston",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "lewisham-dev",
    repoName: "lewishamdevelopmentfinance",
    domain: "lewishamdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "lewisham",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/lewisham`,
    brandName: "Lewisham Development Finance",
    locationName: "Lewisham",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "merton-dev",
    repoName: "mertondevelopmentfinance",
    domain: "mertondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Merton Development Finance",
    locationName: "Merton",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "newham-dev",
    repoName: "newhamdevelopmentfinance",
    domain: "newhamdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "stratford",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/stratford`,
    brandName: "Newham Development Finance",
    locationName: "Newham",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "nottingham-dev",
    repoName: "nottinghamdevelopmentfinance",
    domain: "nottinghamdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "nottinghamshire",
    town: "nottingham",
    ccLocationUrl: `${CC_BASE}/locations/nottinghamshire/nottingham`,
    brandName: "Nottingham Development Finance",
    locationName: "Nottingham",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "richmond-dev",
    repoName: "richmonddevelopmentfinance",
    domain: "richmonddevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "hounslow",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hounslow`,
    brandName: "Richmond Development Finance",
    locationName: "Richmond",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "sutton-dev",
    repoName: "suttondevelopmentfinance",
    domain: "suttondevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "croydon",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/croydon`,
    brandName: "Sutton Development Finance",
    locationName: "Sutton",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "towerhamlets-dev",
    repoName: "towerhamletsdevelopmentfinance",
    domain: "towerhamletsdevelopmentfinance.co.uk",
    type: "development-finance",
    county: "greater-london",
    town: "bermondsey",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/bermondsey`,
    brandName: "Tower Hamlets Development Finance",
    locationName: "Tower Hamlets",
    hostingProvider: "netlify",
    status: "built",
  },
];

// ── Bridging Finance Sites ──────────────────────────────────────────────────

const BRIDGING_SITES: MicrositeConfig[] = [
  {
    slug: "manchester-bridge",
    repoName: "manchesterbridgingfinance",
    domain: "manchesterbridgingfinance.com",
    type: "bridging",
    county: "greater-manchester",
    town: "manchester",
    ccLocationUrl: `${CC_BASE}/locations/greater-manchester/manchester`,
    brandName: "Manchester Bridging Finance",
    locationName: "Manchester",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "camden-bridge",
    repoName: "camdenbridgingfinance",
    domain: "camdenbridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Camden Bridging Finance",
    locationName: "Camden",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "westminster-bridge",
    repoName: "westminsterbridgingfinance",
    domain: "westminsterbridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "bermondsey",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/bermondsey`,
    brandName: "Westminster Bridging Finance",
    locationName: "Westminster",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "kensington-bridge",
    repoName: "kensingtonbridgingfinance",
    domain: "kensingtonbridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Kensington Bridging Finance",
    locationName: "Kensington",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "chelsea-bridge",
    repoName: "chelseabridgingfinance",
    domain: "chelseabridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "brixton",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/brixton`,
    brandName: "Chelsea Bridging Finance",
    locationName: "Chelsea",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "hackney-bridge",
    repoName: "hackneybridgingfinance",
    domain: "hackneybridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Hackney Bridging Finance",
    locationName: "Hackney",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "islington-bridge",
    repoName: "Islingtonbridgingfinance",
    domain: "islingtonbridgingfinance.co.uk",
    type: "bridging",
    county: "greater-london",
    town: "hackney",
    ccLocationUrl: `${CC_BASE}/locations/greater-london/hackney`,
    brandName: "Islington Bridging Finance",
    locationName: "Islington",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "cardiff-bridge",
    repoName: "Cardiffbridgingfinance",
    domain: "cardiffbridgingfinance.co.uk",
    type: "bridging",
    county: "cardiff",
    town: "cardiff-city-centre",
    ccLocationUrl: `${CC_BASE}/locations/cardiff/cardiff-city-centre`,
    brandName: "Cardiff Bridging Finance",
    locationName: "Cardiff",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "bournemouth-bridge",
    repoName: "bridgingloanbournemouth",
    domain: "bridgingloanbournemouth.co.uk",
    type: "bridging",
    county: "dorset",
    town: "bournemouth",
    ccLocationUrl: `${CC_BASE}/locations/dorset/bournemouth`,
    brandName: "Bournemouth Bridging Loans",
    locationName: "Bournemouth",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "plymouth-bridge",
    repoName: "bridgingloanplymouth",
    domain: "bridgingloanplymouth.co.uk",
    type: "bridging",
    county: "devon",
    town: "plymouth",
    ccLocationUrl: `${CC_BASE}/locations/devon/plymouth`,
    brandName: "Plymouth Bridging Loans",
    locationName: "Plymouth",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "brighton-bridge",
    repoName: "bridgingloansbrighton",
    domain: "bridgingloansbrighton.co.uk",
    type: "bridging",
    county: "sussex",
    town: "brighton",
    ccLocationUrl: `${CC_BASE}/locations/sussex/brighton`,
    brandName: "Brighton Bridging Loans",
    locationName: "Brighton",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "wolverhampton-bridge",
    repoName: "bridgingloanwolverhampton",
    domain: "bridgingloanwolverhampton.co.uk",
    type: "bridging",
    county: "west-midlands",
    town: "wolverhampton",
    ccLocationUrl: `${CC_BASE}/locations/west-midlands/wolverhampton`,
    brandName: "Wolverhampton Bridging Loans",
    locationName: "Wolverhampton",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "derby-bridge",
    repoName: "bridgingloanderby",
    domain: "bridgingloanderby.co.uk",
    type: "bridging",
    county: "derbyshire",
    town: "derby",
    ccLocationUrl: `${CC_BASE}/locations/derbyshire/derby`,
    brandName: "Derby Bridging Loans",
    locationName: "Derby",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "hull-bridge",
    repoName: "bridgingloanhull",
    domain: "bridgingloanhull.co.uk",
    type: "bridging",
    county: "east-riding-of-yorkshire",
    town: "hull",
    ccLocationUrl: `${CC_BASE}/locations/east-riding-of-yorkshire/hull`,
    brandName: "Hull Bridging Loans",
    locationName: "Hull",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "luton-bridge",
    repoName: "bridgingloanluton",
    domain: "bridgingloanluton.co.uk",
    type: "bridging",
    county: "bedfordshire",
    town: "luton",
    ccLocationUrl: `${CC_BASE}/locations/bedfordshire/luton`,
    brandName: "Luton Bridging Loans",
    locationName: "Luton",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "middlesbrough-bridge",
    repoName: "bridgingloanmiddlesbrough",
    domain: "bridgingloanmiddlesbrough.co.uk",
    type: "bridging",
    county: "north-yorkshire",
    town: "scarborough",
    ccLocationUrl: `${CC_BASE}/locations/north-yorkshire/scarborough`,
    brandName: "Middlesbrough Bridging Loans",
    locationName: "Middlesbrough",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "norwich-bridge",
    repoName: "bridgingloannorwich",
    domain: "bridgingloannorwich.co.uk",
    type: "bridging",
    county: "norfolk",
    town: "norwich",
    ccLocationUrl: `${CC_BASE}/locations/norfolk/norwich`,
    brandName: "Norwich Bridging Loans",
    locationName: "Norwich",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "peterborough-bridge",
    repoName: "bridgingloanpeterborough",
    domain: "bridgingloanpeterborough.co.uk",
    type: "bridging",
    county: "cambridgeshire",
    town: "peterborough",
    ccLocationUrl: `${CC_BASE}/locations/cambridgeshire/peterborough`,
    brandName: "Peterborough Bridging Loans",
    locationName: "Peterborough",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "reading-bridge",
    repoName: "bridgingloanreading",
    domain: "bridgingloanreading.co.uk",
    type: "bridging",
    county: "berkshire",
    town: "reading",
    ccLocationUrl: `${CC_BASE}/locations/berkshire/reading`,
    brandName: "Reading Bridging Loans",
    locationName: "Reading",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "southampton-bridge",
    repoName: "bridgingloansouthampton",
    domain: "bridgingloansouthampton.co.uk",
    type: "bridging",
    county: "hampshire",
    town: "southampton",
    ccLocationUrl: `${CC_BASE}/locations/hampshire/southampton`,
    brandName: "Southampton Bridging Loans",
    locationName: "Southampton",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "portsmouth-bridge",
    repoName: "bridgingloansportsmouth",
    domain: "bridgingloansportsmouth.co.uk",
    type: "bridging",
    county: "hampshire",
    town: "portsmouth",
    ccLocationUrl: `${CC_BASE}/locations/hampshire/portsmouth`,
    brandName: "Portsmouth Bridging Loans",
    locationName: "Portsmouth",
    hostingProvider: "aws",
    status: "built",
  },
  {
    slug: "stoke-bridge",
    repoName: "bridgingloanstoke",
    domain: "bridgingloanstoke.co.uk",
    type: "bridging",
    county: "staffordshire",
    town: "stoke-on-trent",
    ccLocationUrl: `${CC_BASE}/locations/staffordshire/stoke-on-trent`,
    brandName: "Stoke Bridging Loans",
    locationName: "Stoke-on-Trent",
    hostingProvider: "google",
    status: "built",
  },
  {
    slug: "sunderland-bridge",
    repoName: "bridgingloansunderland",
    domain: "bridgingloansunderland.co.uk",
    type: "bridging",
    county: "tyne-and-wear",
    town: "sunderland",
    ccLocationUrl: `${CC_BASE}/locations/tyne-and-wear/sunderland`,
    brandName: "Sunderland Bridging Loans",
    locationName: "Sunderland",
    hostingProvider: "azure",
    status: "built",
  },
  {
    slug: "swansea-bridge",
    repoName: "bridgingloanswansea",
    domain: "bridgingloanswansea.co.uk",
    type: "bridging",
    county: "swansea",
    town: "swansea-city-centre",
    ccLocationUrl: `${CC_BASE}/locations/swansea/swansea-city-centre`,
    brandName: "Swansea Bridging Loans",
    locationName: "Swansea",
    hostingProvider: "railway",
    status: "built",
  },
  {
    slug: "swindon-bridge",
    repoName: "bridgingloanswindon",
    domain: "bridgingloanswindon.co.uk",
    type: "bridging",
    county: "wiltshire",
    town: "swindon",
    ccLocationUrl: `${CC_BASE}/locations/wiltshire/swindon`,
    brandName: "Swindon Bridging Loans",
    locationName: "Swindon",
    hostingProvider: "netlify",
    status: "built",
  },
];

// ── Niche / Product-Type Sites ──────────────────────────────────────────────

const NICHE_SITES: MicrositeConfig[] = [
  {
    slug: "ssas-property",
    repoName: "ssaspropertyfinance",
    domain: "ssaspropertyfinance.co.uk",
    type: "niche",
    county: "greater-london",
    town: "croydon",
    ccLocationUrl: `${CC_BASE}/services/development-finance`,
    brandName: "SSAS Property Finance",
    locationName: "UK",
    hostingProvider: "netlify",
    status: "built",
  },
  {
    slug: "sipp-property",
    repoName: "sipppropertyfinance",
    domain: "sipppropertyfinance.co.uk",
    type: "niche",
    county: "greater-london",
    town: "croydon",
    ccLocationUrl: `${CC_BASE}/services/development-finance`,
    brandName: "SIPP Property Finance",
    locationName: "UK",
    hostingProvider: "vercel",
    status: "built",
  },
  {
    slug: "tradesman-finance",
    repoName: "tradesmanfinance",
    domain: "tradesmanfinance.co.uk",
    type: "niche",
    county: "greater-london",
    town: "croydon",
    ccLocationUrl: `${CC_BASE}/services/development-finance`,
    brandName: "Tradesman Finance",
    locationName: "UK",
    hostingProvider: "aws",
    status: "built",
  },
];

// ── Combined export ─────────────────────────────────────────────────────────

export const MICROSITES: MicrositeConfig[] = [
  ...DEVELOPMENT_FINANCE_SITES,
  ...BRIDGING_SITES,
  ...NICHE_SITES,
];

export function getMicrositeBySlug(slug: string): MicrositeConfig | undefined {
  return MICROSITES.find((m) => m.slug === slug);
}

export function getMicrositesByType(type: MicrositeConfig["type"]): MicrositeConfig[] {
  return MICROSITES.filter((m) => m.type === type);
}

export function getMicrositesByCounty(county: string): MicrositeConfig[] {
  return MICROSITES.filter((m) => m.county === county);
}

export function getMicrositesByTown(town: string): MicrositeConfig[] {
  return MICROSITES.filter((m) => m.town === town);
}
