/**
 * Promote approved drafts from data/generated/guide-drafts/ into the live
 * guide library at src/lib/guides/content-gap-wave-1.ts.
 *
 * Safety:
 *  - Refuses to promote any draft whose content contains banned compliance
 *    terms (FCA / NACFB / regulated / authorised / Financial Conduct).
 *  - Rejects drafts whose slug collides with an existing GUIDES entry.
 *  - Dry-run by default (--write to commit changes).
 *
 * Usage:
 *   npx tsx scripts/promote-guide-drafts.ts                    # dry-run all drafts
 *   npx tsx scripts/promote-guide-drafts.ts --write            # commit
 *   npx tsx scripts/promote-guide-drafts.ts --slugs a,b --write
 *   npx tsx scripts/promote-guide-drafts.ts --wave 2 --write   # writes content-gap-wave-2.ts
 */

import * as fs from "fs";
import * as path from "path";
import { GUIDES } from "../src/lib/guides/index";
import type { Guide } from "../src/lib/guides/types";
import { checkComplianceFields } from "./lib/compliance";

const ROOT = process.cwd();
const DRAFTS_DIR = path.join(ROOT, "data", "generated", "guide-drafts");
const GUIDES_DIR = path.join(ROOT, "src", "lib", "guides");
const INDEX_FILE = path.join(GUIDES_DIR, "index.ts");

// ─── CLI ────────────────────────────────────────────────────────────────────

interface Args {
  wave: number;
  slugs?: string[];
  write: boolean;
}

function parseArgs(): Args {
  const a = process.argv.slice(2);
  const get = (k: string): string | undefined => {
    const i = a.indexOf(k);
    return i >= 0 ? a[i + 1] : undefined;
  };
  return {
    wave: parseInt(get("--wave") ?? "1", 10),
    slugs: get("--slugs")?.split(",").map((s) => s.trim()),
    write: a.includes("--write"),
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

async function loadDraftFile(file: string): Promise<Guide | null> {
  // tsx handles .ts imports natively. Use a cache-busting query string so
  // re-runs pick up draft edits.
  const mod = await import(`${file}?v=${Date.now()}`);
  const draft = mod.draft ?? mod.default?.draft;
  if (!draft) return null;
  return draft as Guide;
}

function complianceScan(g: Guide): string[] {
  const fields: Array<{ label: string; text: string }> = [
    { label: "title", text: g.title },
    { label: "metaTitle", text: g.metaTitle },
    { label: "metaDescription", text: g.metaDescription },
    { label: "excerpt", text: g.excerpt },
  ];
  for (const s of g.sections) {
    fields.push({ label: `section:${s.heading}`, text: s.heading });
    s.content.forEach((c, i) => fields.push({ label: `section:${s.heading}[${i}]`, text: c }));
  }
  g.faqs?.forEach((f, i) => {
    fields.push({ label: `faq[${i}].q`, text: f.question });
    fields.push({ label: `faq[${i}].a`, text: f.answer });
  });
  return checkComplianceFields(fields).offenders;
}

function emitWaveFile(waveNumber: number, guides: Guide[]): string {
  const header = `// Auto-generated by scripts/promote-guide-drafts.ts — do not edit by hand.
// Source briefs: data/generated/serp-analysis/reports/{slug}.md
// Source drafts: data/generated/guide-drafts/{slug}.ts
// Regenerate via: npx tsx scripts/promote-guide-drafts.ts --wave ${waveNumber} --write

import type { Guide } from "./types";

export const CONTENT_GAP_WAVE_${waveNumber}_GUIDES: Guide[] = `;
  const body = JSON.stringify(guides, null, 2);
  return header + body + ";\n";
}

function patchIndexFile(waveNumber: number): { patched: boolean; file: string } {
  let src = fs.readFileSync(INDEX_FILE, "utf8");
  const importName = `CONTENT_GAP_WAVE_${waveNumber}_GUIDES`;
  const importPath = `./content-gap-wave-${waveNumber}`;

  if (src.includes(importName)) {
    return { patched: false, file: src }; // already wired
  }

  // Add import after the last existing guide import line
  const importLine = `import { ${importName} } from "${importPath}";\n`;
  const lastImportRe = /^import .*? from ".\/[a-zA-Z0-9_-]+";\s*$/gm;
  const matches = [...src.matchAll(lastImportRe)];
  if (matches.length === 0) {
    throw new Error(`Could not locate guide imports in ${INDEX_FILE}`);
  }
  const lastMatch = matches[matches.length - 1];
  const insertAt = lastMatch.index! + lastMatch[0].length;
  src = src.slice(0, insertAt) + "\n" + importLine + src.slice(insertAt);

  // Add spread into the GUIDES array
  const spreadLine = `  ...${importName},`;
  src = src.replace(/(export const GUIDES = \[[\s\S]*?)(\n\];)/, (_m, head, tail) => {
    // Only inject if not already present
    if (head.includes(spreadLine)) return head + tail;
    return head + "\n" + spreadLine + tail;
  });

  return { patched: true, file: src };
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs();

  if (!fs.existsSync(DRAFTS_DIR)) {
    console.error(`No drafts directory: ${DRAFTS_DIR}`);
    process.exit(1);
  }

  const draftFiles = fs
    .readdirSync(DRAFTS_DIR)
    .filter((f) => f.endsWith(".ts") && !f.startsWith("_"))
    .map((f) => path.join(DRAFTS_DIR, f));

  console.log(`Found ${draftFiles.length} draft files in ${path.relative(ROOT, DRAFTS_DIR)}`);

  const existingSlugs = new Set(GUIDES.map((g) => g.slug));
  const accepted: Guide[] = [];
  const rejected: Array<{ slug: string; reasons: string[] }> = [];

  for (const file of draftFiles) {
    const slugFromFile = path.basename(file, ".ts");
    if (args.slugs && !args.slugs.includes(slugFromFile)) continue;

    const draft = await loadDraftFile(file);
    if (!draft) {
      rejected.push({ slug: slugFromFile, reasons: ["no `draft` export"] });
      continue;
    }

    const reasons: string[] = [];
    if (draft.slug !== slugFromFile) reasons.push(`slug mismatch: file=${slugFromFile}, draft.slug=${draft.slug}`);
    if (existingSlugs.has(draft.slug)) reasons.push(`slug already in live GUIDES`);
    const offenders = complianceScan(draft);
    if (offenders.length) reasons.push(`compliance: ${offenders.slice(0, 3).join("; ")}`);
    if (draft.sections.length < 3) reasons.push(`only ${draft.sections.length} sections`);
    const wordCount = draft.sections.flatMap((s) => s.content).join(" ").split(/\s+/).filter(Boolean).length;
    if (wordCount < 1200) reasons.push(`only ${wordCount} words (threshold 1200)`);

    if (reasons.length) {
      rejected.push({ slug: draft.slug, reasons });
    } else {
      accepted.push(draft);
    }
  }

  accepted.sort((a, b) => a.slug.localeCompare(b.slug));

  console.log(`\n✓ Accepted: ${accepted.length}`);
  accepted.forEach((g) => {
    const wc = g.sections.flatMap((s) => s.content).join(" ").split(/\s+/).filter(Boolean).length;
    console.log(`  - ${g.slug.padEnd(50)} ${g.sections.length}s / ${g.faqs?.length ?? 0}f / ${wc}w`);
  });

  if (rejected.length) {
    console.log(`\n✗ Rejected: ${rejected.length}`);
    rejected.forEach((r) => {
      console.log(`  - ${r.slug}`);
      r.reasons.forEach((x) => console.log(`      · ${x}`));
    });
  }

  if (!args.write) {
    console.log(`\n[dry-run] Re-run with --write to commit these changes:`);
    console.log(`  1. Write src/lib/guides/content-gap-wave-${args.wave}.ts`);
    console.log(`  2. Patch src/lib/guides/index.ts to import + spread CONTENT_GAP_WAVE_${args.wave}_GUIDES`);
    return;
  }

  if (accepted.length === 0) {
    console.log(`\nNo accepted drafts — nothing to promote.`);
    return;
  }

  // Write wave file
  const waveFile = path.join(GUIDES_DIR, `content-gap-wave-${args.wave}.ts`);
  fs.writeFileSync(waveFile, emitWaveFile(args.wave, accepted));
  console.log(`\n✓ Wrote ${path.relative(ROOT, waveFile)}`);

  // Patch index
  const { patched, file: patchedSrc } = patchIndexFile(args.wave);
  if (patched) {
    fs.writeFileSync(INDEX_FILE, patchedSrc);
    console.log(`✓ Patched ${path.relative(ROOT, INDEX_FILE)}`);
  } else {
    console.log(`✓ ${path.relative(ROOT, INDEX_FILE)} already wired`);
  }

  console.log(`\nNext steps:`);
  console.log(`  npm run lint:fix && npm run type-check`);
  console.log(`  npx tsx scripts/generate-sitemaps.ts`);
  console.log(`  npm run dev  # verify /guides/{slug} pages render`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
