import type { CalculatorContent } from "./types";

export const content: CalculatorContent = {
  howItWorks: {
    title: "How Cash-on-Cash Return Is Calculated",
    paragraphs: [
      "Cash-on-cash return (CoC) measures the annual pre-tax cash income generated by a property as a percentage of the total cash you have invested in it. It is the most practical metric for leveraged property investors because it focuses entirely on actual cash received and actual cash deployed - not paper gains, not theoretical yields against full property value.",
      "The calculation is straightforward. You take your annual net cash flow - rent received minus all cash costs including mortgage payments, management fees, insurance, maintenance, and any service charges - and divide it by your total cash invested. Total cash invested is your deposit plus all acquisition costs: Stamp Duty Land Tax, legal fees, survey, mortgage arrangement fees, and any refurbishment spend before the property was let.",
      "The key distinction from rental yield is that cash-on-cash return accounts for the cost of debt. A property might show a 6% gross yield, but if your mortgage rate consumes most of that income, your actual cash-on-cash return could be 2% to 3% or even negative. This makes CoC a far more useful operational metric than yield for investors who are borrowing to purchase.",
      "This calculator models your annual cash flow on a property-by-property basis, using your actual mortgage rate, letting costs, and void assumption to produce a realistic CoC figure. You can adjust the LTV to see how different deposit amounts change your cash-on-cash return, and model the impact of refurbishment spend on both rental income and the CoC rate.",
    ],
  },
  guide: {
    title: "Cash-on-Cash Return: The Essential Metric for Leveraged Property Investors",
    sections: [
      {
        heading: "Why Cash-on-Cash Return Matters for Leveraged Investors",
        paragraphs: [
          "For a cash buyer, rental yield and cash-on-cash return are essentially the same metric - there is no mortgage payment to account for. The moment you introduce debt, the two diverge, and the divergence tells you something critical about whether a deal is genuinely cash generative.",
          "Consider a property worth £250,000 generating £13,000 per year in gross rent - a 5.2% gross yield. After costs of £3,000 (management, insurance, maintenance, voids), net income is £10,000. A cash buyer's net yield is 4%. Now introduce a 75% LTV mortgage of £187,500 at a 5.2% interest rate. Annual interest is approximately £9,750. After costs of £3,000 and interest of £9,750, annual cash flow is just £250 on a cash invested figure of roughly £78,000 (£62,500 deposit plus £15,500 in acquisition costs). The cash-on-cash return is 0.3% - barely above zero.",
          "This example illustrates why so many landlords found their portfolios cash-flow negative when mortgage rates rose sharply from 2022 onwards. Properties that appeared profitable on a yield basis became cash-flow drains once debt service costs were factored in. Cash-on-cash return is the metric that would have flagged this risk at the point of purchase, and it is the metric that should be central to every acquisition decision made in a higher-rate environment.",
        ],
        bullets: [
          "CoC return below 0%: property is cash-flow negative - income does not cover all costs including mortgage",
          "CoC return of 0–4%: thin margin; vulnerable to rate rises, void periods, or unexpected costs",
          "CoC return of 5–8%: solid performance for a leveraged investment in the current rate environment",
          "CoC return of 8–12%: strong performance; typical of well-bought northern properties or value-add strategies",
          "CoC return above 12%: exceptional; usually requires below-market purchase, significant refurbishment uplift, or HMO/SA income strategy",
        ],
      },
      {
        heading: "What Constitutes a Good Cash-on-Cash Return in the UK Market",
        paragraphs: [
          "There is no single universally correct threshold for cash-on-cash return, because the answer depends on your investment objectives, tax position, access to alternative opportunities, and the stage of the market cycle you are investing in. That said, experienced UK portfolio investors generally regard a CoC return of 8% to 12% as the target range for deals that meaningfully compound portfolio wealth.",
          "Below 6%, most investors struggle to justify the illiquidity and management overhead of buy-to-let compared to alternatives. A 5% CoC return on a heavily managed property is arguably less attractive than a less labour-intensive income-producing asset, particularly for investors whose time has a high opportunity cost. The exception is where a low CoC return is accepted in exchange for strong capital growth prospects - a London zone 2 flat at 3% CoC might be rational for an investor who is confident in 5% to 7% annual capital growth and has the income to absorb negative cash flow.",
          "Above 12%, deals generally involve some form of value creation or specialist strategy. HMO properties converting a standard house into a five or six-bedroom shared house can dramatically increase rental income per square foot, improving CoC returns substantially. Serviced accommodation - Airbnb and corporate short lets - can deliver headline CoC returns of 15% to 25% in the right locations, though occupancy risk, management intensity, and the regulatory environment (councils increasingly restricting short lets) must be factored in. Commercial conversions and small-scale development can also produce high CoC returns on the cash deployed, though these carry development risk that standard BTL does not.",
        ],
      },
      {
        heading: "Improving CoC Through Refurb-and-Refinance (the BRRR Strategy)",
        paragraphs: [
          "The Buy, Refurbish, Refinance, Rent - or BRRR - strategy is the most systematic approach to improving cash-on-cash return by reducing the net cash invested in a property. The logic is straightforward: purchase a below-market property requiring work, add value through refurbishment, refinance against the improved value to recover some or all of your original cash, then rent the property out. If executed correctly, the refurbished value supports a higher mortgage than the original all-in cost, meaning you recover your deposit and refurbishment spend entirely and hold the asset with little or no net cash invested.",
          "A simplified example: purchase a property for £130,000 in poor condition. Spend £20,000 on a full refurbishment. Total cash invested: £150,000 (plus SDLT and acquisition costs, say £5,000). Post-refurbishment, the property is valued at £195,000. Refinancing at 75% LTV produces a mortgage of £146,250 - recovering £146,250 of your £155,000 cash outlay. The net cash remaining in the deal is approximately £8,750. If the property generates £800 per month in rent, with costs and mortgage interest consuming £700, the £100 per month surplus represents a cash-on-cash return of approximately 13.7% on the £8,750 remaining. More importantly, the £146,250 recovered can be redeployed into the next deal.",
          "BRRR is not without execution risk. Refurbishment costs can overrun. Post-refurbishment valuations can disappoint if the local comparables do not support the hoped-for figure. Mortgage products may not be available at 75% LTV on the new value immediately after refurbishment - most lenders require a six-month ownership period before refinancing. Bridging finance is often used to fund the purchase and works, with the exit via a BTL refinance once the hold period condition is met. The bridging finance cost - typically 0.8% to 1.2% per month - must be factored into the overall deal economics.",
        ],
        bullets: [
          "BRRR requires below-market purchase: focus on distressed vendors, probate, or properties needing cosmetic to moderate structural work",
          "Refurbishment budget discipline is critical: get multiple contractor quotes and build in a 15–20% contingency",
          "Six-month rule: most BTL lenders require six months' ownership before refinancing; plan your bridging accordingly",
          "The deal works best when refinanced value is at least 130% of total acquisition and refurbishment cost",
          "Track your 'money left in' figure precisely - it is the denominator of your CoC return calculation",
          "Successful BRRR investors typically complete 3–6 cycles per year, growing portfolios rapidly with recycled capital",
        ],
      },
      {
        heading: "Comparing Investment Opportunities Using Cash-on-Cash Return",
        paragraphs: [
          "One of the most valuable applications of cash-on-cash return is as a standardised basis for comparing investment opportunities that superficially look very different. A £400,000 London flat and an £80,000 Northern terraced house require very different absolute capital commitments and offer very different risk profiles, but expressing both as a CoC return on capital deployed makes comparison meaningful.",
          "When comparing deals using CoC, ensure your assumptions are consistent. Use the same void period assumption (industry standard is 4 to 6 weeks per year), the same maintenance allowance (1% of property value annually), and the same mortgage rate - even if the actual products differ - if you are trying to isolate the asset-level performance from the financing. This allows you to see which property is intrinsically the stronger income generator before financing differences are introduced.",
          "CoC return should not be used in isolation. A deal with a 10% CoC return in a structurally declining market with poor liquidity and high void risk may be less attractive than a 6% CoC return in a regenerating city with strong tenant demand and clear capital growth prospects. The best deal analysis combines CoC (for current income performance), projected total ROI (for the full return picture including growth), and a qualitative assessment of market fundamentals and downside risk. Used together, these metrics provide the foundation for disciplined, repeatable investment decision-making.",
        ],
      },
    ],
  },
};
