import type { CalculatorContent } from "./types";

export const content: CalculatorContent = {
  howItWorks: {
    title: "How the construction timeline calculator works",
    paragraphs: [
      "This calculator produces an estimated construction programme for your development based on project type, scale (number of units or gross internal area), construction method, and location. Enter your scheme parameters and the calculator generates a phased timeline from site preparation through practical completion, together with a finance cost projection showing how rolled-up interest accumulates across the programme. The output is designed to help you structure your development finance facility with a realistic loan term and drawdown schedule rather than an optimistic one that creates problems mid-project.",
      "Timeline estimates are derived from BCIS output benchmarks and industry programme norms for each development type. Traditional masonry construction for new-build residential schemes typically progresses at 3 to 5 units per week for a well-resourced medium-sized contractor, falling to 1 to 2 units per week for more complex or smaller schemes with limited site access. Modern Methods of Construction (MMC) programmes - volumetric modular or structural insulated panel (SIP) systems - are calculated differently, with significant time front-loaded into factory production before site installation begins. Both routes are modelled in the calculator.",
      "The finance cost projection models interest accrual on a realistic drawdown curve. Development finance is drawn down in stages as works progress rather than in a single lump sum on day one. A typical 12-unit residential scheme might draw 15% at commencement for preliminaries and substructure, with subsequent tranches released against QS-certified milestones: slab completion, roof on, first fix, second fix, and practical completion. Because interest is charged only on drawn balances, not on the full facility, the actual interest cost is materially lower than a flat headline rate applied to the total loan would suggest.",
      "These estimates are indicative starting points. Actual programme depends on contractor capacity, weather, site-specific complexity, and the supply chain conditions prevailing at the time of procurement. Always obtain a contractor's indicative programme before finalising your loan term request, and build in a minimum 3-month buffer beyond the contractor's estimate to account for the delays that affect virtually every construction project.",
    ],
  },
  guide: {
    title: "Construction timelines in UK property development: phasing, delays, and finance implications",
    sections: [
      {
        heading: "Programme phasing for different development types",
        paragraphs: [
          "Different development types have fundamentally different programme structures, and understanding the typical phasing for your specific scheme type is essential for accurate finance cost modelling. New-build residential schemes - the most common development type funded through specialist development finance - typically follow a clear sequential programme from site clearance through to practical completion. However, the programme logic differs significantly between detached houses, terraced houses, apartment blocks, and mixed-use schemes.",
          "For a new-build detached house or small cluster of houses (1 to 5 units), the programme is relatively simple and sequential. Site preparation and groundworks typically take 4 to 8 weeks. Brickwork and block to wall plate runs at approximately 2 to 3 weeks per unit for a two-storey property with a competent masonry subcontractor. Roof structure and covering adds 1 to 2 weeks per unit. First fix (structural carpentry, plumbing, and electrical rough-in) takes 2 to 4 weeks per unit, followed by insulation, plasterboard, and plastering at 2 to 3 weeks, and second fix and decoration at 3 to 5 weeks. A well-managed detached house can therefore achieve practical completion in approximately 24 to 36 weeks from site start.",
          "Apartment blocks follow a different logic because the multiple units can be built in parallel once the structure is erected. A 10-unit apartment block with a concrete frame typically takes 6 to 10 weeks for foundations and ground floor slab, then 2 to 3 weeks per floor for the concrete frame (or 2 to 4 weeks per floor for masonry), and 4 to 8 weeks for the roof. Once the structure is watertight, internal fit-out of all units proceeds simultaneously with a team working floor by floor. The total programme for a 10-unit, 3-storey apartment block is typically 40 to 52 weeks for a traditional build.",
          "Mixed-use schemes add complexity because the commercial element often has different specification requirements, different occupier timetables, and sometimes different contractors to the residential portion. Category A fit-out of commercial space (structural, M&E, and base finishes suitable for a tenant to take) adds 8 to 16 weeks to the residential programme. If the commercial space is pre-let to a tenant who requires a specific Category B fit-out (full occupier fit-out), the developer may be carrying a double programme: the residential sales programme and the commercial tenant's fit-out programme, which need to be coordinated carefully to avoid the residential scheme competing with the commercial fit-out for the same trades.",
        ],
        bullets: [
          "Single detached house: 24-36 weeks from site start to practical completion",
          "Small residential cluster (2-5 units): 32-48 weeks, with units completing in sequence",
          "10-unit apartment block (traditional): 40-52 weeks",
          "20-30 unit residential scheme: 60-80 weeks for traditional build",
          "Mixed-use schemes: add 8-16 weeks for commercial Category A fit-out",
        ],
      },
      {
        heading: "Critical path factors and programme risk",
        paragraphs: [
          "The critical path in a construction programme is the sequence of activities that directly determines the overall duration of the project. Any delay to a critical path activity delays the entire project, while delays to non-critical activities can be absorbed within programme float without affecting the completion date. Identifying the critical path for your specific project and actively managing the risks along it is the most effective form of programme risk management available to developers.",
          "For most UK residential new-build schemes, the critical path runs through: planning condition discharge (particularly for pre-commencement conditions that must be resolved before breaking ground), groundworks and foundations (heavily weather-dependent and difficult to accelerate once started), structural frame or masonry (requires consistent subcontractor output), mechanical and electrical first fix (frequently a bottleneck due to trade availability), and plastering (the trade that often creates the most unplanned delay because it follows directly from first fix and requires drying time before second fix can begin).",
          "Planning conditions are one of the most frequently overlooked programme risks. A planning consent is typically accompanied by a schedule of pre-commencement conditions - conditions that must be formally discharged by the LPA before any development works can begin. These might include archaeological watching brief arrangements, construction management plans, materials approval, surface water drainage details, and noise mitigation schemes. Discharging pre-commencement conditions requires submission to the LPA, a statutory determination period of 8 weeks, and potentially further rounds of submission if the LPA requires amendments. In practice, condition discharge can add 8 to 16 weeks to the period between planning grant and site start - a significant delay that should be incorporated into your pre-application programme from day one.",
          "Contractor insolvency is one of the highest-impact programme risks and one that is not adequately reflected in most developers' risk registers. A main contractor insolvency mid-construction requires the developer to: secure the site, conduct a forensic assessment of work completed and work outstanding, negotiate with the bonding company if a performance bond is in place, and re-tender the remaining works to a replacement contractor at prevailing market rates. This process typically takes 6 to 12 weeks minimum before construction can restart, at which point there may be damage to partially completed works, disputes with subcontractors over retention, and disruption to the supply chain. Performance bonds from contractors are available but not universal - insisting on a bond from a contractor of limited financial strength is a worthwhile cost.",
        ],
        bullets: [
          "Pre-commencement condition discharge typically adds 8-16 weeks before site start",
          "Groundworks and foundations are the most weather-sensitive phase - plan for a 2-4 week buffer",
          "M&E first fix is the most commonly cited bottleneck due to trade availability",
          "Contractor insolvency adds a minimum 6-12 weeks for re-mobilisation",
          "Performance bonds are available from contractors - consider requiring them for contracts above £500K",
        ],
      },
      {
        heading: "Weather, supply chain delays, and how to build in resilience",
        paragraphs: [
          "The UK construction industry is significantly affected by adverse weather, particularly during the winter months between November and February. Groundworks cannot proceed during prolonged frost, brickwork is restricted in temperatures below 2°C, and concrete pours require specific temperature controls that add cost and time in cold conditions. Schemes that are planned to commence groundworks in October or November face a higher risk of weather-related delays than those starting in April or May, when a full summer of programme is available before winter conditions return.",
          "The practical response is to sequence major weather-sensitive activities to avoid the worst winter months where possible, and to build weather contingency explicitly into the programme rather than treating it as an unplanned risk. A programme for a scheme starting groundworks in September should carry a 3 to 4 week weather contingency for groundworks and substructure to account for the November to February risk window. A scheme starting in March or April can typically apply a smaller 1 to 2 week weather contingency for the same activities. Monitoring surveyors and experienced lenders will scrutinise whether your programme accounts for seasonal risk - a programme that shows no weather contingency for winter groundworks will be challenged at underwriting.",
          "Supply chain disruption has become an increasingly significant programme risk for UK developers since 2021. Lead times for structural steel (relevant to apartment blocks and commercial schemes), roofing materials, electrical distribution equipment, and certain M&E components have extended substantially and remain unpredictable. Structural steel lead times that were historically 8 to 10 weeks extended to 24 to 30 weeks during the supply disruptions of 2021 to 2023, and while they have partially recovered, they remain more variable than pre-pandemic norms. Procuring long-lead items early - placing orders for structural steel, roof trusses, windows, and M&E equipment before or at the time of construction contract execution - is one of the most effective ways to protect the programme.",
          "Programme resilience is also built through contractor selection and procurement strategy. Two-stage procurement - engaging a preferred contractor early to carry out preliminary design and planning stages for a fee, with a binding fixed-price contract agreed before RIBA Stage 4 - builds contractor knowledge and buy-in that reduces the risk of post-contract surprises. Contractors who understand the scheme thoroughly before pricing it are less likely to submit a price that requires value engineering changes mid-construction. Early contractor involvement also allows the contractor to pre-order long-lead items and secure subcontractor slots before construction commences, meaningfully reducing programme risk from day one.",
        ],
        bullets: [
          "Groundworks and brickwork are restricted by frost - avoid November to February starts where possible",
          "Build 3-4 weeks of weather contingency into programmes running through winter months",
          "Pre-order structural steel, roof trusses, and M&E equipment before construction contract execution",
          "Two-stage procurement builds contractor knowledge and reduces post-contract surprises",
          "Document all weather and supply chain delays formally - they are relevant to force majeure provisions in your development finance facility",
        ],
      },
      {
        heading: "How construction timeline affects development finance costs",
        paragraphs: [
          "The relationship between your construction programme and your total finance cost is direct and linear: every additional month of programme extension increases your rolled-up interest liability by one month's interest on drawn balances. For a £2 million development finance facility drawn down at an average of 60% over a 12-month programme (average drawn balance of £1.2 million) at 8% per annum, the interest cost is approximately £96,000. If the programme extends to 15 months, the interest cost rises to approximately £120,000 - an increase of £24,000 for a 3-month delay. Extend to 18 months and the cost reaches approximately £144,000.",
          "Finance costs do not scale linearly with loan balance across the programme. In the early months, when only preliminaries and groundworks have been drawn, the interest accruing is relatively modest. As the build programme progresses and more tranches are drawn, the accruing interest accelerates. A delay in the final stages of a project - perhaps because of a snagging dispute with the contractor, a slow sales market, or a hold-up on Building Control sign-off - is proportionally more expensive than the same delay in the early stages, because it affects interest on a much larger drawn balance.",
          "Traditional versus Modern Methods of Construction (MMC) have materially different programme and finance cost profiles. A traditional masonry 20-unit residential scheme might take 18 months from site start to practical completion, with costs drawn progressively over that period. A comparable MMC volumetric modular scheme might deliver practical completion in 12 months from factory production commencing - but the cost profile is front-loaded, with a significant proportion of costs committed to the factory months before any units are installed on site. This front-loading means higher average drawn balances in the early programme stages, partially offsetting the finance cost saving from the shorter overall programme. The net finance cost advantage of MMC over traditional build depends on the specific drawdown profile and should always be modelled explicitly.",
          "Construction Capital works with developers at the appraisal stage to model the finance cost implications of different programme scenarios. Understanding the finance cost sensitivity to programme extension - and the cost-benefit of paying a premium for a faster contractor or a higher-specification MMC solution - is one of the most valuable analyses a developer can commission before committing to a procurement strategy. Submit your programme and drawdown assumptions through our Deal Room and we will model the finance cost implications alongside indicative lender terms.",
        ],
        bullets: [
          "Every additional month of programme adds one month of rolled-up interest on drawn balances",
          "Late-programme delays are disproportionately expensive because drawn balances are at their peak",
          "MMC front-loads costs to the factory production phase - model the drawdown profile carefully",
          "Building Control sign-off and pre-completion sales periods are frequently underestimated in programme",
          "Request a 3-month extension buffer from your lender at the outset - extending mid-build costs more than planning ahead",
        ],
      },
    ],
  },
};
