import type { CalculatorContent } from "./types";

export const content: CalculatorContent = {
  howItWorks: {
    title: "How Rental Yield Is Calculated",
    paragraphs: [
      "Rental yield is the annual rental income generated by a property expressed as a percentage of its purchase price or current market value. It is the most widely used metric for comparing investment properties at a glance and is the starting point for any buy-to-let analysis.",
      "Gross rental yield is the simpler of the two figures. You divide the annual rent by the property value and multiply by 100. For example, a property worth £200,000 generating £10,000 per year in rent produces a gross yield of 5%. This headline number is useful for quickly screening deals but it tells you nothing about what you actually keep after costs.",
      "Net rental yield strips out the running costs of ownership - letting agent fees, landlord insurance, service charges, ground rent, maintenance allowances, and void periods - before performing the same calculation. A property yielding 5% gross might deliver only 3.5% net once those costs are accounted for. Net yield is a far more honest representation of investment performance and the number lenders increasingly focus on when assessing affordability.",
      "This calculator allows you to enter both your gross rent and your expected annual costs so you can model both figures side by side. You can also switch between purchase price and current market value as the denominator, which matters when assessing yield on a property you already own and are comparing against a refinance or disposal.",
    ],
  },
  guide: {
    title: "Rental Yield: A Complete Guide for UK Property Investors",
    sections: [
      {
        heading: "What Yields to Expect Across UK Regions",
        paragraphs: [
          "Rental yield varies enormously across the UK and is broadly inversely correlated with capital values. London and the South East have some of the highest property prices in the country, which compresses gross yields to between 3% and 5% in most areas. Prime central London postcodes - Mayfair, Knightsbridge, Chelsea - often trade at sub-3% gross yields, meaning investors are buying primarily for long-term capital growth rather than current income.",
          "Move north and the income story changes substantially. Cities such as Manchester, Leeds, Liverpool, Sheffield, and Newcastle routinely offer gross yields of 6% to 9% on standard residential stock. Certain pockets of the North West and the Midlands, particularly where HMO or multi-let strategies are viable, can push yields above 10% on a gross basis. The North East - Sunderland, Middlesbrough, Durham - has historically offered some of the highest headline yields in England, though investors should account for slower liquidity and higher management intensity in those markets.",
          "Wales offers attractive yields in cities like Cardiff (5-7%) and across the valleys where entry prices are lower. Scotland operates under a different regulatory regime - the Private Residential Tenancy replaced assured shorthold tenancies - but cities like Dundee and Glasgow have consistently offered gross yields of 7% to 10%. Northern Ireland, and Belfast in particular, remains one of the highest-yielding markets in the UK at 6% to 9% gross.",
        ],
        bullets: [
          "London (prime): 2.5–4% gross yield, strong long-term capital growth",
          "London (outer zones and commuter belt): 4–5.5% gross yield",
          "Birmingham, Manchester, Leeds city centres: 5.5–8% gross yield",
          "Liverpool, Sheffield, Newcastle: 6–9% gross yield",
          "North East, parts of Wales: 8–12% gross yield on selective stock",
          "HMO and multi-let strategies can add 2–4 percentage points above standard BTL yields in most regions",
        ],
      },
      {
        heading: "Costs That Reduce Your Net Yield",
        paragraphs: [
          "Gross yield figures quoted by estate agents and property portals rarely reflect what an investor actually receives. A thorough net yield calculation must account for all the costs of ownership and management. Letting agent fees alone can consume 8% to 15% of gross rent depending on whether you use a let-only, rent collection, or fully managed service. Landlords with multiple properties sometimes negotiate lower percentage fees, but the headline cost remains significant.",
          "Void periods - the time between tenancies when no rent is received - should be modelled at a minimum of 4 to 6 weeks per year for most markets, and more in areas with higher tenant turnover or seasonal demand. Maintenance and repairs are frequently underestimated by newer landlords. A rule of thumb is to budget 1% of property value per year, though older stock, leasehold flats, and HMOs typically cost more.",
          "For leasehold properties, ground rent and service charges represent genuine cash costs that directly reduce net yield. Annual service charges on newer purpose-built flats can run to £2,000 to £5,000 or more, and ground rent - where it still applies on older leases - adds further drag. Landlord buildings insurance, contents insurance for furnished lets, gas safety certificates, electrical installation condition reports (EICRs), and energy performance certificates (EPCs) all represent recurring compliance costs.",
        ],
        bullets: [
          "Letting agent fees: 8–15% of gross annual rent",
          "Void periods: allow 4–8 weeks per year (more in higher-turnover markets)",
          "Maintenance and repairs: budget 1% of property value annually",
          "Service charges on leasehold property: £1,500–£6,000+ per year",
          "Landlord insurance: £200–£600 per year depending on property type",
          "Compliance costs: gas safety, EICR, EPC, HMO licensing where applicable",
          "Mortgage arrangement fees and legal costs: amortise over the hold period",
        ],
      },
      {
        heading: "Yield vs Capital Growth: Finding the Right Balance",
        paragraphs: [
          "One of the most important strategic decisions for any property investor is where to position on the yield-versus-growth spectrum. High-yield markets typically offer strong current income but more modest long-term price appreciation. Low-yield markets often reflect strong demand fundamentals and planning constraints that support sustained capital growth, but may generate negative cash flow on a leveraged basis - particularly after the changes introduced by Section 24.",
          "Neither approach is universally superior. A portfolio built around high-yield northern properties may generate strong monthly cash flow but prove harder to refinance at attractive LTVs if values stagnate. A portfolio concentrated in London and the South East may build substantial equity over time but require the investor to fund negative cash flow from other income sources in the interim - a strategy that carried greater risk after mortgage interest relief was phased out.",
          "Most professional portfolio landlords seek a blend: core capital growth assets in locations with constrained supply, supplemented by higher-yielding properties or strategies (HMOs, serviced accommodation, commercial-to-residential conversions) that generate the cash flow needed to service the overall portfolio and fund further acquisitions. The optimal balance depends on your tax position, borrowing capacity, and investment horizon.",
        ],
      },
      {
        heading: "Section 24 and Its Impact on Net Returns",
        paragraphs: [
          "Section 24 of the Finance (No. 2) Act 2015 - commonly called the 'landlord tax' - fundamentally changed the economics of leveraged buy-to-let for higher and additional rate taxpayers holding property in personal names. Before its phased introduction between 2017 and 2020, landlords could deduct 100% of mortgage interest from rental income before calculating their tax liability. Section 24 replaced this with a basic rate (20%) tax credit on finance costs regardless of the landlord's marginal rate.",
          "The practical consequence is that a higher rate taxpayer with significant mortgage borrowing may now pay tax on a profit they do not actually receive in cash. A landlord generating £20,000 in rent, paying £15,000 in mortgage interest, and incurring £3,000 in other costs previously had a taxable profit of £2,000. Under Section 24, they are taxed on £17,000 (rent minus non-finance costs), receiving only a 20% credit on the £15,000 interest - resulting in a tax bill that can exceed their actual cash profit.",
          "For this reason, many higher rate taxpaying landlords have either sold properties where yields were too thin to absorb the additional tax burden, or have transferred ownership to a limited company structure. Limited companies are not subject to Section 24 and can still deduct mortgage interest as a business expense, paying corporation tax only on genuine profit. The trade-off involves higher mortgage rates on limited company BTL products, SDLT on any transfer of existing properties, and the complexities of extracting profit from a company tax-efficiently. Taking advice from a tax specialist before making structural decisions is essential.",
        ],
      },
    ],
  },
};
